### ISSUE TITLE
Specifying multiple clusters in config.yaml causes panic

### ISSUE THREAD

**Issue by mikouaj** [google/gke-policy-automation#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Debug Output

N/A

### Panic Output

https://gist.github.com/mikouaj/cf1df1fa33a9d3638d9cfbfa5283fb4c

### Steps to Reproduce

1. Create zconfig.yaml` file with a two clusters and local policy dir i.e.
```
clusters:
  - name: public-zonal
    project: XXX
    location: europe-west2-a
  - name: private-regional-nochannel
    project: XXX
    location: europe-central2
policies:
  - local: ./gke-policies
```

2. Run `./gke-policy cluster review -c config.yaml`

### Expected Behavior

Application should print evaluation output for each cluster

### Actual Behavior

Application panics

### References

N / A
