### ISSUE TITLE
Policy Evaluation result JSON output to Cloud Storage

### ISSUE THREAD

**Issue by mikouaj** [google/gke-policy-automation#34]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Introduce possibility of storing JSON policy evaluation results in a Cloud Storage bucket.

- [x] #32
- [x] Introduce Cloud Storage writer of JSON results
- [x] introduce configuration file option to trigger JSON serialisation to Cloud Storage bucket

### References

N/A

**Comment by rickygodoy** [comment]
Waiting on #58 to implement this last task.

```
- cloudStorage:
      bucket: some-bucket
      path?prefix?: some/bla/bla
```

**Comment by rickygodoy** [comment]
It was implemented and tested on my cluster:

```
silent: false
clusters:
  - name: gke-1
    project: godoy-sandbox-344913
    location: us-central1-c
outputs:
  - cloudStorage:
      bucket: godoy-sandbox-test
      path: results.json
```
